### ISSUE TITLE
With local fs name that differs from remote fs name, the PVCs cannot be used

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi-driver#50]
If I use a different local name for a remote fs, then the PVCs cannot be used. I can see this error:
failed to provision volume with StorageClass "csi-spectrum-scale-remotefset": rpc error: code = Internal desc = Unable to get Mount Details for FS [fs0_1m] in Primary cluster

**Comment by smitaraut** [comment]
Can you describe the storageclass csi-spectrum-scale-remotefset?

**Comment by yadaven** [comment]
For volumeBackendFs we need to use local FS name. e.g 
1. we have remote cluster with FS gpfs2
2. On local cluster gpfs2 (remote cluster FS) is remotely mounted as rgpfs2
3. So in volumeBackendFS we need to use rgpfs2.

So in above case remoteFs name is different from localFsName. 

I think you are using remoteFs name in storageClass for volumeBackend name.  Kindly let us know if it fix the problem.

We will make sure in our documentation this step is clearly mentioned.

**Comment by przem123** [comment]
Tried this storage class before for my test but it did not work. `remote_fs0_1m` is local fs name for remote `fs0_1m`:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-spectrum-scale-remotefset
provisioner: csi-spectrum-scale
parameters:
    volBackendFs: "fs0_1m"
    localFs: "remote_fs0_1m"
    clusterId: "4473793006880872527"
reclaimPolicy: Delete
```
You mean I should use remote fs name as `localFs` and local name as `volBackendFs`?
